language: python
python:
  - "2.7"
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - /tmp/proto3.1.0

install:
  - pip install pip --upgrade
  - pip install setuptools
  - python setup.py sdist
  - pip install dist/ga4gh*.tar.gz -c constraints.txt
# every installable in setup.py's entry_points should be tested here
  - ga2vcf --version
  - ga2sam --version

before_script:
  - pip install -r dev-requirements.txt
    
# run_tests.py runs everything under the script: tag so only put commands
# under it that we want to run (and want to be able to run) as local tests
script: 
  - flake8 ga2sam_dev.py ga2vcf_dev.py
           setup.py
           tests ga4gh
  - python -mnose tests 
              --with-coverage --cover-package ga4gh.converters
              --cover-inclusive --cover-min-percentage 85
              --cover-branches --cover-erase
  - make clean -C docs
  - make -C docs
